---
- name: Install Docker on Ubuntu and RHEL
  hosts: all
  become: yes
  tasks:
   

    - name: Install dependencies for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: ansible_facts.distribution == "Ubuntu"

    - name: Add Docker GPG key (Ubuntu)
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_facts.distribution == "Ubuntu"

    - name: Add Docker repository (Ubuntu)
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
      when: ansible_facts.distribution == "Ubuntu"

    - name: Install Docker (Ubuntu)
      apt:
        name: docker-ce
        state: present
      when: ansible_facts.distribution == "Ubuntu"

    - name: Install dependencies for Docker (RHEL)
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
      when: ansible_facts.distribution == "RedHat"

    - name: Add Docker repository (RHEL)
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      when: ansible_facts.distribution == "RedHat"

    - name: Install Docker (RHEL)
      yum:
        name: docker-ce
        state: present
      when: ansible_facts.distribution == "RedHat"

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Enable Docker service
      service:
        name: docker
        enabled: yes
    - shell: mkdir /home/docker

    - name: copy our docker file for image run
      copy:
        src: ./Dockerfile
        dest: /home/docker/Dockerfile
      
    - name: run docker file
      shell: docker image build -t /home/docker/Dockerfile image:latest
